# LICENSE
# This software is the exclusive property of Gencovery SAS.
# The use and distribution of this software is prohibited without the prior consent of Gencovery SAS.
# About us: https://gencovery.com
from __future__ import annotations

from typing import TYPE_CHECKING, Type

from gws_core.config.config_types import ConfigSpecs
from gws_core.config.param.param_spec import ParamSpec
from gws_core.core.classes.jsonable import DictJsonable
from gws_core.resource.view.lazy_view_param import LazyViewParam

from .view import View
from .view_types import ViewSpecs

if TYPE_CHECKING:
    from gws_core.resource.resource import Resource

METHOD_SPEC_PREFIX: str = 'method_'
VIEW_SPEC_PREFIX: str = 'view_'


class ResourceViewMetaData():
    method_name: str
    view_type: Type[View]
    human_name: str
    short_description: str
    specs: ViewSpecs
    default_view: bool
    hide: bool

    def __init__(self, method_name: str, view_type: Type[View],
                 human_name: str, short_description: str,
                 specs: ViewSpecs, default_view: bool, hide: bool) -> None:
        self.method_name = method_name
        self.view_type = view_type
        self.human_name = human_name
        self.short_description = short_description
        self.specs = specs
        self.default_view = default_view
        self.hide = hide

    def clone(self) -> 'ResourceViewMetaData':
        return ResourceViewMetaData(
            self.method_name, self.view_type, self.human_name, self.short_description, self.specs, self.default_view,
            self.hide)

    def to_json(self) -> dict:
        return {
            "method_name": self.method_name,
            "view_type": self.view_type._type,
            "human_name": self.human_name,
            "short_description": self.short_description,
            "default_view": self.default_view,
        }

    def to_complete_json(self, resource: Resource = None) -> dict:
        json_ = self.to_json()

        jsonable_dict = DictJsonable(self._get_view_specs(resource, skip_private=True))
        json_["config_specs"] = jsonable_dict.to_json()

        return json_

    def get_view_specs_from_resource(self, resource: Resource, skip_private: bool = False) -> ConfigSpecs:
        return self._get_view_specs(resource, skip_private=skip_private)

    def get_view_specs_from_type(self, skip_private: bool = False) -> ConfigSpecs:
        return self._get_view_specs(skip_private=skip_private)

    def _get_view_specs(self, resource: Resource = None, skip_private: bool = False) -> ConfigSpecs:
        """Return the config spec for a view of a resource. It converts the ViewSpecs to ConfigSpecs by
        replacing the LazyViewParam to ParamSpec.

        If a resource is provided, the LazyViewParam is replaced with the ParamSpec, otherwise, the default
        param spec of the LazyViewParam is used

        """
        specs = {**self.view_type._specs, **self.specs}
        config_specs: ConfigSpecs = {}

        for key, value in specs.items():
            spec: ParamSpec = None
            if isinstance(value, LazyViewParam):

                # if the resource is provided, generate the paramspec
                if resource:
                    spec = value.generate_param_spec(resource)
                else:
                    # otherwise, use the default param spec value
                    spec = value.default_param_spec

            else:
                spec = value

            # skip the private specs
            if skip_private and spec.visibility == 'private':
                continue

            # Replace the lazy spec with the ParamSpec generated by the function
            config_specs[key] = spec
        return config_specs
