from typing import Dict

from fastapi import status

from gws_core.core.exception.exception_response import ExceptionShowMode

from .base_http_exception import BaseHTTPException


class BadRequestException(BaseHTTPException):
    """
    Generic exception to throw a 400 error useful for any kind of error
    """

    def __init__(
        self,
        detail: str,
        unique_code: str = None,
        detail_args: Dict = None,
        headers: Dict = None,
        instance_id: str = None,
        show_as: ExceptionShowMode = "error",
    ) -> None:
        """Throw a generic exception

        :param http_status_code: HTTP error code
        :type http_status_code: int
        :param detail: Human redable message of the error
        :type detail: str
        :param unique_code: Unique code to recognize the error,
        if not provided, a code is generated with filename and method name (that raised the exception), defaults to None
        If can also  be use for internationalisation (translating the detail message)
        :type unique_code: str, optional
        :param detail_args: if provided, it replace the arg in the detail message (between double bracket {{}}) with the corresponding dict value, defaults to None
        For example : detail = 'Hello {{name}}' and detail_args = {"name" : "Bob"}, the message that will be show will be 'Hello bob'
        This is useful for internationalisation
        :type detail_args: Dict, optional
        :param headers: if specific header need to be returned in the HTTP response, defaults to None
        :type headers: Dict, optional
        :param instance_id: Unique id for this exception instance. Only provide when it was generated by another exception
        :type instance_id: str, optional
        :param show_as: Mode to show the error in the interface, if error it will be showed in an error box.
                        If info, in info box. , defaults to 'error'
        """

        super().__init__(
            http_status_code=status.HTTP_400_BAD_REQUEST,
            detail=detail,
            unique_code=unique_code,
            detail_args=detail_args,
            headers=headers,
            instance_id=instance_id,
            show_as=show_as,
        )
