import uuid

from fastapi import HTTPException

from ..exception_response import ExceptionShowMode


class BaseHTTPException(HTTPException):
    """
    Generic exception
    All the exception that extends this exceptions are considered a excepted exceptions and
    those are not logged in the console nor the logging file
    """

    detail: str
    unique_code: str
    detail_args: dict
    headers: dict
    instance_id: str
    show_as: ExceptionShowMode

    def __init__(
        self,
        http_status_code: int,
        detail: str,
        unique_code: str = None,
        detail_args: dict = None,
        headers: dict = None,
        instance_id: str = None,
        show_as: ExceptionShowMode = "error",
    ) -> None:
        """Throw a generic exception

        :param http_status_code: HTTP error code
        :type http_status_code: int
        :param detail: Human redable message of the error
        :type detail: str
        :param unique_code: Unique code to recognize the error,
        if not provided, a code is generated with filename and method name (that raised the exception), defaults to None
        If can also  be use for internationalisation (translating the detail message)
        :type unique_code: str, optional
        :param detail_args: if provided, it replace the arg in the detail message (between double bracket {{}}) with the corresponding dict value, defaults to None
        For example : detail = 'Hello {{name}}' and detail_args = {"name" : "Bob"}, the message that will be show will be 'Hello bob'
        This is useful for internationalisation
        :type detail_args: Dict, optional
        :param headers: if specific header need to be returned in the HTTP response, defaults to None
        :type headers: Dict, optional
        :param instance_id: Unique id for this exception instance. Only provide when it was generated by another exception
        :type instance_id: str, optional
        :param show_as: Mode to show the error in the interface, if error it will be showed in an error box.
                        If info, in info box. , defaults to 'error'
        :type show_as: ExceptionType, optional
        """
        super().__init__(status_code=http_status_code, detail=detail)
        self.detail = detail
        self.detail_args = detail_args

        self.unique_code = unique_code
        self.headers = headers
        self.show_as = show_as

        if instance_id is not None:
            self.instance_id = instance_id
        else:
            self.instance_id = str(uuid.uuid4())

    def get_detail_with_args(self) -> str:
        """Replace the arguments in the exception message with dict corresponding values
        For example : detail = 'Hello {{name}}' and detail_args = {"name" : "Bob"}, the message that will be show will be 'Hello bob'
        """

        replaced_detail: str = self.detail

        if self.detail_args:
            for key in self.detail_args:
                replaced_detail = replaced_detail.replace(
                    "{{" + key + "}}", str(self.detail_args[key])
                )

        return replaced_detail

    def __str__(self) -> str:
        return self.get_detail_with_args()
