

from enum import Enum
from typing import Optional

from gws_core.core.model.model_dto import BaseModelDTO
from gws_core.core.model.model_with_user_dto import ModelWithUserDTO
from gws_core.experiment.experiment_dto import ExperimentSimpleDTO
from gws_core.impl.file.fs_node_model_dto import FsNodeModelDTO
from gws_core.model.typing_dto import TypingRefDTO, TypingStatus
from gws_core.model.typing_style import TypingStyle
from gws_core.project.project_dto import ProjectDTO


class ResourceOrigin(Enum):
    # If the resource was imported manually by the user
    UPLOADED = "UPLOADED"
    # Generated by a task
    GENERATED = "GENERATED"
    # If the resource was imported manually by the user from another lab
    IMPORTED_FROM_LAB = "IMPORTED_FROM_LAB"
    # For project DOCUMENT where this lab work as a S3 server
    S3_PROJECT_STORAGE = "S3_PROJECT_STORAGE"


class ResourceDTO(ModelWithUserDTO):
    resource_typing_name: str
    resource_type: Optional[TypingRefDTO] = None
    fs_node: Optional[FsNodeModelDTO]
    is_downloadable: bool
    origin: ResourceOrigin
    name: str
    has_children: bool
    type_status: TypingStatus
    flagged: bool
    experiment: Optional[ExperimentSimpleDTO]
    project: Optional[ProjectDTO]
    style: TypingStyle


class ResourceSimpleDTO(BaseModelDTO):
    id: str
    name: str
