from gws_core.core.classes.observer.message_dispatcher import MessageDispatcher
from gws_core.folder.space_folder import SpaceFolder
from gws_core.protocol.protocol_model import ProtocolModel
from gws_core.resource.resource_dto import ResourceModelExportDTO, ResourceOrigin
from gws_core.resource.resource_model import ResourceModel
from gws_core.scenario.scenario import Scenario
from gws_core.task.task_model import TaskModel
from gws_core.user.user import User


class ResourceModelLoader:
    """Class to load a ResourceModel from a ResourceModelExportDTO.

    Handles resolving the scenario and task model that generated the resource:
    - If the DTO references the provided scenario, it links to it and looks up
      the task model from the provided protocol model.
    - If the DTO references a different scenario, it tries to find the existing
      scenario and task model in the lab database. If not found, the resource is
      loaded without a scenario/task link and an info message is dispatched.
    """

    _dto: ResourceModelExportDTO

    def __init__(self, dto: ResourceModelExportDTO) -> None:
        self._dto = dto

    def load_resource_model(
        self,
        scenario: Scenario | None = None,
        protocol_model: ProtocolModel | None = None,
        origin: ResourceOrigin | None = None,
        message_dispatcher: MessageDispatcher | None = None,
    ) -> ResourceModel:
        """Create a ResourceModel from a ResourceModelExportDTO.

        This sets the persistable fields from the DTO. Computed fields like
        is_downloadable, has_children, type_status, and is_application are
        derived at read time and are not stored.

        It resolves the scenario and task model that generated this resource:
        - If the DTO references the provided scenario, it links to it and looks up
          the task model from the provided protocol model.
        - If the DTO references a different scenario, it tries to find the existing
          scenario and task model in the lab database. If not found, the resource is
          loaded without a scenario/task link and an info message is dispatched.

        :param scenario: the scenario being imported (used to match resource ownership)
        :param protocol_model: the protocol model of the scenario (used to look up task models)
        :param origin: optional origin override, if not provided uses the DTO origin
        :param message_dispatcher: optional dispatcher for info messages
        :return: the resource model (not yet saved to DB)
        """
        dto = self._dto

        resolved_scenario: Scenario | None = None
        resolved_task_model: TaskModel | None = None

        # If the resource was generated by a scenario
        if dto.scenario and dto.task_model_id:
            # if the resource was generated by this scenario
            if scenario and dto.scenario.id == scenario.id:
                resolved_scenario = scenario
                if protocol_model:
                    process_model = protocol_model.get_process_by_id(dto.task_model_id)
                    if not process_model or not isinstance(process_model, TaskModel):
                        raise Exception(
                            f"Task model with id {dto.task_model_id} not found for resource model {dto.id}"
                        )
                    resolved_task_model = process_model
            else:
                # If the resource was not generated by this scenario
                # We try to find the scenario and task model in the lab,
                # if not available, we leave None
                existing_scenario = Scenario.get_by_id(dto.scenario.id)
                existing_task = TaskModel.get_by_id(dto.task_model_id)

                if existing_scenario and existing_task:
                    resolved_scenario = existing_scenario
                    resolved_task_model = existing_task
                else:
                    dispatcher = message_dispatcher or MessageDispatcher()
                    dispatcher.notify_info_message(
                        f"Resource model '{dto.name}' references scenario '{dto.scenario.title}' and task model with id '{dto.task_model_id}' which could not be found in the lab. The resource will be loaded without linking it to the scenario and task."
                    )

        resource_model = ResourceModel()
        resource_model.id = dto.id
        resource_model.created_at = dto.created_at
        resource_model.created_by = User.get_by_id_and_check(dto.created_by.id)
        resource_model.last_modified_at = dto.last_modified_at
        resource_model.last_modified_by = User.get_by_id_and_check(dto.last_modified_by.id)
        resource_model.resource_typing_name = dto.resource_typing_name
        resource_model.name = dto.name
        resource_model.origin = origin if origin is not None else dto.origin
        resource_model.flagged = dto.flagged
        # If SpaceFolder.get_by_id returns None, it is not a problem
        resource_model.folder = SpaceFolder.get_by_id(dto.folder.id) if dto.folder else None
        resource_model.style = dto.style
        resource_model.parent_resource_id = dto.parent_resource_id
        resource_model.generated_by_port_name = dto.generated_by_port_name
        resource_model.content_is_deleted = True
        resource_model.scenario = resolved_scenario
        resource_model.task_model = resolved_task_model
        return resource_model
