from datetime import datetime
from enum import Enum

from gws_core.core.model.model_dto import BaseModelDTO
from gws_core.core.model.model_with_user_dto import ModelWithUserDTO
from gws_core.folder.space_folder_dto import SpaceFolderDTO
from gws_core.impl.file.fs_node_model_dto import FsNodeModelDTO
from gws_core.model.typing_dto import TypingRefDTO, TypingStatus
from gws_core.model.typing_style import TypingStyle
from gws_core.scenario.scenario_dto import ScenarioSimpleDTO


class ResourceOrigin(Enum):
    # If the resource was imported manually by the user
    UPLOADED = "UPLOADED"
    # Generated by a task
    GENERATED = "GENERATED"
    # If the resource was imported manually by the user from another lab
    IMPORTED_FROM_LAB = "IMPORTED_FROM_LAB"
    # For folder DOCUMENT where this lab work as a S3 server
    S3_FOLDER_STORAGE = "S3_FOLDER_STORAGE"


class ResourceModelDTO(ModelWithUserDTO):
    resource_typing_name: str
    resource_type: TypingRefDTO | None = None
    fs_node: FsNodeModelDTO | None
    is_downloadable: bool
    origin: ResourceOrigin
    name: str
    has_children: bool
    type_status: TypingStatus
    flagged: bool
    scenario: ScenarioSimpleDTO | None
    folder: SpaceFolderDTO | None
    style: TypingStyle
    is_application: bool


class ResourceSimpleDTO(BaseModelDTO):
    id: str
    name: str


class ShareResourceWithSpaceRequestDTO(BaseModelDTO):
    folder_id: str
    valid_until: datetime | None = None
