# LICENSE
# This software is the exclusive property of Gencovery SAS.
# The use and distribution of this software is prohibited without the prior consent of Gencovery SAS.
# About us: https://gencovery.com

from enum import Enum


class GWSException(Enum):
    INTERNAL_SERVER_ERROR = "Internal server error"
    WRONG_CREDENTIALS = "Wrong email or password"
    WRONG_CREDENTIALS_INVALID_API_KEY = "Not authorized. Invalid API key"
    WRONG_CREDENTIALS_USER_NOT_FOUND = "Not authorized. Cannot generate user access token. User not found"
    WRONG_CREDENTIALS_USER_NOT_ACTIVATED = "Not authorized. Cannot generate user access token. User not active"
    INVALID_TOKEN = "Not authorized. Invalid token"
    FUNCTIONALITY_UNAVAILBLE_IN_PROD = "This functionnality is not available in the production environment"
    MISSING_PROD_API_URL = "Missing production API URL"
    ERROR_DURING_DEV_LOGIN = "Error during login in development environment"
    CENTRAL_API_DEV_DISABLED = "The centrals routes are disabled in dev"
    OBJECT_ID_NOT_FOUND = "{{objectName}} with id : '{{id}}' not found"
    USER_NOT_ACTIVATED = "User not activated"
    RESOURCE_NOT_COMPATIBLE = "Trying to set an incompatible resource to port '{{port}}'. Resource type: '{{resource_type}}', excepted types : '{{expected_types}}'."
    MISSING_CONFIG_PARAMS = "The mandatory configs '{{param_names}}' are missing."
    UNKNOWN_CONFIG_PARAMS = "The parameter '{{param_name}}' does not exist in the config."
    INVALID_PARAM_VALUE = "Invalid value '{{param_value}}' for the parameter '{{param_name}}'. Error : {{error}}"
    EXPERIMENT_RUN_EXCEPTION = "{{error}} {{context}} | Experiment : '{{experiment}}'"
    TASK_BUILD_EXCEPTION = "{{error}} | Task : '{{instance_name}}'"
    PROTOCOL_BUILD_EXCEPTION = "{{error}} | Protocol : '{{instance_name}}'"
    MISSING_INPUT_RESOURCES = "The inputs '{{port_names}}' were not provided but are mandatory"
    IMCOMPATIBLE_PORT = "Invalid connection, port are imcompatible. The output '{{out_port_name}}' types {{out_port_types}} can't be converted to input '{{in_port_name}}' types {{in_port_types}}"
    EXPERIMENT_STOPPED_MANUALLY = "Experiment manually stopped by a user."
    EXPERIMENT_ERROR_BEFORE_RUN = "Error before running the experiment."
    TASK_CHECK_BEFORE_STOP = "Check before task returned false. Reason: {{message}}"
    EXPERIMENT_VALIDATE_RUNNING = "Can't validate a running experiment"
    RESET_ERROR_RESOURCE_USED_IN_ANOTHER_EXPERIMENT = "Can't reset the experiment because the output resource '{{resource_model_name}}' is used in experiment '{{experiment}}'"
    DELETE_GENERATED_RESOURCE_ERROR = "This resource was generatd by a task, it cannot be deleted. Only imported resource can be deleted"
    RESOURCE_USED_ERROR = "This resource is used in the experiment '{{experiment}}', it can't be modified nor deleted"
    INVALID_UNIQUE_CODE = "Not authorized. Invalid url"
    INVALID_LINKED_RESOURCE = "The resource generated on port {{port_name}} is linked to another resource which is not a input of the task. This break the tracability."
    REPORT_VALIDATED = "The report can't be updated not delete because it is validated"
    REPORT_EXP_ALREADY_ASSOCIATED = "The experiment is already associated with the report"
    REPORT_VALIDATION_EXP_NOT_VALIDATED = "The associated experiment '{{title}}' must be validated first"
    REPORT_VALIDATION_EXP_NO_PROJECT = "The associated experiment '{{title}}' is not link to a the report's project"
    REPORT_VALIDATION_EXP_OTHER_PROJECT = "The associated experiment '{{title}}' is linked to another project"
    REPORT_VALIDATION_RESOURCE_VIEW_OTHER_EXP = "The view '{{view_name}}' is from the experiment '{{exp_title}} but this experiment is not linked to the report. Please link this experiment to the report."
    REPORT_ADD_EXP_OTHER_PROJECT = "Can't associate the experiment to the report because they are in different projects"
    EMPTY_FILE = "The file '{{filename}}' is empty"
    INVALID_FILE_ON_UPLOAD = "The file is invalid. Error : '{{error}}'"
    INVALID_FOLDER_ON_UPLOAD = "The folder is invalid. Error : '{{error}}'"
    REPORT_NO_ASSOCIATED_EXPERIMENT = "The report is not associated with an experiment. Please associate it to an experiment to access views."
