# LICENSE
# This software is the exclusive property of Gencovery SAS.
# The use and distribution of this software is prohibited without the prior consent of Gencovery SAS.
# About us: https://gencovery.com


from pandas import DataFrame

from gws_core.config.config_types import ConfigParams, ConfigSpecs
from gws_core.config.param.param_spec import TextParam
from gws_core.impl.live.helper.live_code_helper import LiveCodeHelper
from gws_core.impl.openai.open_ai_chat import OpenAiChat
from gws_core.impl.openai.open_ai_chat_param import OpenAiChatParam
from gws_core.impl.openai.open_ai_helper import OpenAiHelper
from gws_core.impl.table.table import Table
from gws_core.impl.text.text import Text
from gws_core.io.io_spec import InputSpec, OutputSpec
from gws_core.io.io_spec_helper import InputSpecs, OutputSpecs
from gws_core.task.task import Task
from gws_core.task.task_decorator import task_decorator
from gws_core.task.task_io import TaskInputs, TaskOutputs


@task_decorator("SmartTableTransformer", human_name="Smart table transformer",
                short_description="Table transformer that uses AI  (OpenAI).")
class TableSmartTransformer(Task):
    """
This task is still in beta version.

This task uses openAI API to generate python code that transforms a dataframe. This code is then automatically executed.

/!\ This task does not support table tags.

The data of the table is not transferered to OpenAI, only the provided text.
    """

    input_specs: InputSpecs = {
        'source': InputSpec(Table),
    }
    output_specs: OutputSpecs = {
        'target': OutputSpec(Table),
        'generated_code': OutputSpec(Text),
    }
    config_specs: ConfigSpecs = {
        'prompt': OpenAiChatParam()
    }

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:

        # get the table
        table: Table = inputs["source"]

        context = f"Your are a developer assistant that generate code in python to transform a dataframe.The variable named 'input' contains the dataframe. The transformed dataframe must be assigned to a variable named 'output'. {OpenAiHelper.generate_code_rules} The dataframe has {table.nb_rows} rows and {table.nb_columns} columns."

        chat: OpenAiChat = OpenAiChat.from_json(
            params.get_value("prompt"), context=context)

        # only call open ai if the last message is from the user
        if chat.last_message_is_user():
            # create the completion
            self.log_info_message('Generating code snippet...')

            chat = OpenAiHelper.call_gpt(chat)

        # save the new config with the new prompt
        self.update_config({'prompt': chat.to_json()})

        code = chat.get_last_assistant_message(extract_code=True)
        if code is None:
            raise Exception("No code generated by OpenAI")

        self.log_info_message(
            'Code generated by OpenAI: ' + code)

        # execute the live code
        self.log_info_message('Executing the code snippet...')
        init_globals = {'self': self, "input": table.get_data(), **globals()}
        outputs = LiveCodeHelper.run_python_code(code, init_globals)
        output = outputs.get("output", None)

        if not isinstance(output, DataFrame):
            raise Exception("The output must be a pandas DataFrame")

        result = Table(output)
        return {'target': result, 'generated_code': Text(code)}
