from typing import cast
from unittest import TestCase

from gws_core.apps.app_dto import AppProcessStatus
from gws_core.apps.app_process import AppProcess
from gws_core.apps.app_resource import AppResource
from gws_core.apps.apps_manager import AppsManager
from gws_core.config.config_params import ConfigParams
from gws_core.resource.resource import Resource
from gws_core.resource.resource_dto import ResourceOrigin
from gws_core.resource.resource_model import ResourceModel
from gws_core.scenario.scenario_proxy import ScenarioProxy
from gws_core.task.task import Task
from gws_core.task.task_runner import TaskRunner


class AppTester:
    """Helper class to test that an app (Reflex or Streamlit) starts and runs correctly.

    Usage with a task that generates the app:
        AppTester.test_app_from_task(
            test_case=self,
            generate_task_type=GenerateReflexShowcaseApp,
            app_output_name="reflex_app",
            input_resources={"resource": table},
        )

    Usage with an existing AppResource:
        AppTester.test_app(self, app_resource)
    """

    @staticmethod
    def test_app_from_task(
        test_case: TestCase,
        generate_task_type: type[Task],
        app_output_name: str,
        input_resources: dict[str, Resource] | None = None,
        config_values: dict | None = None,
    ) -> None:
        """Run a task to generate an AppResource, then test that the app starts and runs correctly.
        It tests that the resource generated by the generate_task_type can be started as an app,
        that the app process is running, and that the health check endpoint returns a successful response.
        It also tests that the app process can be stopped.

        :param test_case: The unittest.TestCase instance (used for assertions).
        :param generate_task_type: The task class that generates the AppResource.
        :param app_output_name: The name of the task output port that produces the AppResource.
        :param input_resources: Optional dict mapping input port names to resources.
            Resources will be saved as ResourceModels and connected as sources.
        :param config_values: Optional dict of config param values to set on the task.
        """

        scenario_proxy = ScenarioProxy()
        protocol_proxy = scenario_proxy.get_protocol()
        generate_task = protocol_proxy.add_task(generate_task_type, "generate")

        if input_resources:
            for port_name, resource in input_resources.items():
                resource_model = ResourceModel.save_from_resource(
                    resource, origin=ResourceOrigin.UPLOADED
                )
                protocol_proxy.add_source(
                    port_name, resource_model.id, generate_task.get_input_port(port_name)
                )

        if config_values:
            generate_task.set_config_params(config_values)

        scenario_proxy.run()

        generate_task = generate_task.refresh()
        app_resource = cast(AppResource, generate_task.get_output(app_output_name))

        AppTester.test_app(test_case, app_resource)

    @staticmethod
    def test_app_from_task_runner(
        test_case: TestCase,
        generate_task_type: type[Task],
        app_output_name: str,
        input_resources: dict[str, Resource] | None = None,
        config_values: dict | None = None,
    ) -> None:
        """Run a task using TaskRunner to generate an AppResource, then test that the app starts
        and runs correctly. This is a lighter alternative to test_app_from_task that does not
        require creating a full scenario.

        :param test_case: The unittest.TestCase instance (used for assertions).
        :param generate_task_type: The task class that generates the AppResource.
        :param app_output_name: The name of the task output port that produces the AppResource.
        :param input_resources: Optional dict mapping input port names to resources.
        :param config_values: Optional dict of config param values to set on the task.
        """

        task_runner = TaskRunner(
            task_type=generate_task_type,
            params=config_values,
            inputs=input_resources,
        )

        task_runner.run()

        app_resource = cast(AppResource, task_runner.get_output(app_output_name))

        resource_model = ResourceModel.save_from_resource(
            app_resource, origin=ResourceOrigin.UPLOADED
        )
        app_resource = cast(AppResource, resource_model.get_resource())

        AppTester.test_app(test_case, app_resource)

    @staticmethod
    def test_app(test_case: TestCase, app_resource: AppResource) -> None:
        """Test that an app resource starts and runs correctly.

        :param test_case: The unittest.TestCase instance (used for assertions).
        :param app_resource: The app resource to test. Must already be saved as a ResourceModel.
        """
        # make the check faster to avoid test block
        AppProcess.CHECK_RUNNING_INTERVAL = 3

        try:
            # start the app
            app_resource.default_view(ConfigParams())

            app_process = AppsManager.find_app_by_resource_model_id(app_resource.get_model_id())

            if app_process is None:
                test_case.fail("No app process found")

            app_process.wait_for_start()
            if not app_process.is_running():
                test_case.fail("App process is not running")

            # check if the app is running
            test_case.assertTrue(app_process.call_health_check())

            status = app_process.get_status_dto()
            test_case.assertEqual(status.status, AppProcessStatus.RUNNING)
            test_case.assertEqual(status.app.app_resource_id, app_resource.get_model_id())

            AppsManager.stop_all_processes()

            # check if the app is stopped
            test_case.assertFalse(app_process.call_health_check())
            test_case.assertFalse(app_process.subprocess_is_running())
        finally:
            AppsManager.stop_all_processes()
