from peewee import CompositeKey, ForeignKeyField, ModelSelect

from gws_core.core.model.base_model import BaseModel
from gws_core.form_template.form_template import FormTemplate
from gws_core.form_template.form_template_version import FormTemplateVersion
from gws_core.note_template.note_template import NoteTemplate


class NoteTemplateFormTemplateModel(BaseModel):
    """Join row mirroring `FORM_TEMPLATE` rich-text blocks embedded in a
    `NoteTemplate`.

    Source of truth is the rich-text block payload; this row is a queryable
    projection reconciled by the form module's NoteTemplateContentUpdatedEvent
    listener whenever note-template content changes. See spec §3.6.

    Joins on `FormTemplateVersion` (the pinned version) so we can answer
    "is anyone still pinning this exact archived version?". The denormalized
    `form_template` column lets queries skip the join through the version
    when the family-level question suffices.
    """

    note_template: NoteTemplate = ForeignKeyField(
        NoteTemplate, null=False, index=True, on_delete="CASCADE"
    )
    form_template_version: FormTemplateVersion = ForeignKeyField(
        FormTemplateVersion, null=False, index=True, on_delete="RESTRICT"
    )
    form_template: FormTemplate = ForeignKeyField(
        FormTemplate, null=False, index=True, on_delete="RESTRICT"
    )

    # Auto-generated by Peewee from the template FK. Annotated here so type
    # checkers see the raw-id accessor (avoids loading the related row).
    form_template_version_id: str

    @classmethod
    def get_by_note_template(cls, note_template_id: str) -> list["NoteTemplateFormTemplateModel"]:
        return list(cls.select().where(cls.note_template == note_template_id))

    @classmethod
    def get_by_form_template_version(cls, version_id: str) -> ModelSelect:
        return cls.select().where(cls.form_template_version == version_id)

    @classmethod
    def count_by_form_template_version(cls, version_id: str) -> int:
        return cls.select().where(cls.form_template_version == version_id).count()

    @classmethod
    def get_by_form_template(cls, template_id: str) -> ModelSelect:
        return cls.select().where(cls.form_template == template_id)

    @classmethod
    def upsert(cls, note_template_id: str, version_id: str, template_id: str) -> None:
        """Insert a (note_template, version) row if missing.

        The denormalized form_template column is set from the version row,
        so callers pass it explicitly rather than re-deriving inside this
        method (the listener already has the version loaded). No update
        path: the (note_template, version) pair fully determines
        form_template.
        """
        if (
            cls.select()
            .where(
                (cls.note_template == note_template_id) & (cls.form_template_version == version_id)
            )
            .exists()
        ):
            return
        cls(
            note_template=note_template_id,
            form_template_version=version_id,
            form_template=template_id,
        ).save()

    @classmethod
    def delete_for(cls, note_template_id: str, version_id: str) -> None:
        """Remove the join row for (note_template, version). No-op if
        absent."""
        cls.delete().where(
            (cls.note_template == note_template_id) & (cls.form_template_version == version_id)
        ).execute()

    def save(self, *args, **kwargs) -> "BaseModel":
        return super().save(*args, force_insert=True, **kwargs)

    class Meta:
        table_name = "gws_note_template_form_template"
        is_table = True
        primary_key = CompositeKey("note_template", "form_template_version")
