from peewee import BooleanField, CompositeKey, ForeignKeyField, ModelSelect

from gws_core.core.model.base_model import BaseModel
from gws_core.form.form import Form

from .note import Note


class NoteFormModel(BaseModel):
    """Join row mirroring `FORM` rich-text blocks embedded in a `Note`.

    Source of truth is the rich-text block payload; this row is a queryable
    projection reconciled by the form module's NoteContentUpdatedEvent
    listener whenever note content changes. See spec §3.6.
    """

    note: Note = ForeignKeyField(Note, null=False, index=True, on_delete="CASCADE")
    form: Form = ForeignKeyField(Form, null=False, index=True, on_delete="RESTRICT")
    is_owner = BooleanField(default=False)

    # Auto-generated by Peewee from the template FK. Annotated here so type
    # checkers see the raw-id accessor (avoids loading the related row).
    form_id: str

    @classmethod
    def get_by_note(cls, note_id: str) -> list["NoteFormModel"]:
        return list(cls.select().where(cls.note == note_id))

    @classmethod
    def get_by_form(cls, form_id: str) -> ModelSelect:
        return cls.select().where(cls.form == form_id)

    @classmethod
    def count_by_form(cls, form_id: str) -> int:
        return cls.select().where(cls.form == form_id).count()

    @classmethod
    def get_owners_of_note(cls, note_id: str) -> list["NoteFormModel"]:
        return list(
            cls.select().where(
                (cls.note == note_id) & (cls.is_owner == True)  # noqa: E712
            )
        )

    @classmethod
    def has_other_references(cls, form_id: str, exclude_note_id: str) -> bool:
        return cls.select().where((cls.form == form_id) & (cls.note != exclude_note_id)).exists()

    @classmethod
    def upsert(cls, note_id: str, form_id: str, is_owner: bool) -> None:
        """Insert a (note, form) row if missing, or update is_owner if it
        drifted. Used by the NoteContentUpdatedEvent listener to reconcile
        the join with rich-text content; centralizes the composite-key
        insert/update dance in one place.
        """
        existing = cls.get_or_none(
            (cls.note == note_id) & (cls.form == form_id)
        )
        if existing is None:
            cls(note=note_id, form=form_id, is_owner=is_owner).save()
        elif existing.is_owner != is_owner:
            cls.update(is_owner=is_owner).where(
                (cls.note == note_id) & (cls.form == form_id)
            ).execute()

    @classmethod
    def delete_for(cls, note_id: str, form_id: str) -> None:
        """Remove the join row for (note, form). No-op if absent."""
        cls.delete().where(
            (cls.note == note_id) & (cls.form == form_id)
        ).execute()

    def save(self, *args, **kwargs) -> "BaseModel":
        return super().save(*args, force_insert=True, **kwargs)

    class Meta:
        table_name = "gws_note_form"
        is_table = True
        primary_key = CompositeKey("note", "form")
