from fastapi import Depends, Query

from gws_core.core.classes.search_builder import SearchParams
from gws_core.core.model.model_dto import PageDTO
from gws_core.core_controller import core_app
from gws_core.lab.lab_model.lab_dto import LabDTO, LabDTOWithCredentials
from gws_core.lab.lab_model.lab_model_service import LabModelService
from gws_core.user.authorization_service import AuthorizationService


########################## CREATION ROUTES ##########################
@core_app.get(
    "/lab/generate-code-url",
    tags=["Lab"],
    summary="Generate a URL with a unique code for lab registration",
)
def generate_code_url(
    _=Depends(AuthorizationService.check_user_access_token),
) -> dict:
    """Generate a URL with a unique code for lab registration."""
    return {"url": LabModelService.generate_unique_code_url()}


@core_app.post(
    "/lab/register-from-url",
    tags=["Lab"],
    summary="Register this lab to another lab using a code URL",
)
def register_lab_from_url(
    url: str,
    _=Depends(AuthorizationService.check_user_access_token),
) -> LabDTO:
    """Called on the second lab by the user. Takes the full URL generated by the first lab,
    extracts the code, and calls the first lab's /lab/from-code endpoint with the current lab info."""
    return LabModelService.register_lab_from_url(url)


@core_app.post("/lab/from-code", tags=["Lab"], summary="Create or update a lab from a unique code")
def create_lab_from_code(
    lab_dto: LabDTO,
    code: str = Query(
        "code", description="The unique code to validate, passed as a query parameter"
    ),
) -> LabDTOWithCredentials:
    """Create or update a lab from a unique code. No auth required — code-based validation.
    This is called by another lab with the generated code."""
    return LabModelService.create_or_update_lab_from_code(code, lab_dto)


################################### READ ROUTES ###################################
@core_app.get("/lab/{id_}", tags=["Lab"], summary="Get a lab by id")
def get_lab_by_id(
    id_: str,
    _=Depends(AuthorizationService.check_user_access_token),
) -> LabDTO:
    """Get a lab by its database id."""
    return LabModelService.get_by_id(id_).to_dto()


@core_app.post("/lab/search", tags=["Lab"], summary="Search labs")
def search_labs(
    search_dict: SearchParams,
    page: int | None = 1,
    number_of_items_per_page: int | None = 20,
    _=Depends(AuthorizationService.check_user_access_token),
) -> PageDTO[LabDTO]:
    """Search labs using a search builder."""
    return LabModelService.search(search_dict, page, number_of_items_per_page).to_dto()
