from gws_core.core.classes.paginator import Paginator
from gws_core.core.classes.search_builder import SearchParams
from gws_core.core.exception.exceptions.bad_request_exception import (
    BadRequestException,
)
from gws_core.core.exception.gws_exceptions import GWSException
from gws_core.core.service.external_api_service import ExternalApiService
from gws_core.core.utils.settings import Settings
from gws_core.core.utils.string_helper import StringHelper
from gws_core.credentials.credentials import Credentials
from gws_core.credentials.credentials_service import CredentialsService
from gws_core.credentials.credentials_type import (
    CredentialsDataLab,
    SaveCredentialsDTO,
)
from gws_core.external_lab.external_lab_api_service import ExternalLabApiService
from gws_core.lab.lab_model.lab_dto import LabDTO, LabDTOWithCredentials
from gws_core.lab.lab_model.lab_model import LabModel
from gws_core.lab.lab_model.lab_model_search_builder import LabModelSearchBuilder
from gws_core.protocol.protocol_model import ProtocolModel
from gws_core.scenario.scenario import Scenario
from gws_core.share.shared_resource import SharedResource
from gws_core.share.shared_scenario import SharedScenario
from gws_core.task.task_model import TaskModel
from gws_core.user.current_user_service import AuthenticateUser
from gws_core.user.unique_code_service import UniqueCodeService
from gws_core.user.user import User


class LabModelService:
    """Service for lab model operations with unique-code-based URL generation."""

    @classmethod
    def generate_unique_code_url(cls) -> str:
        """Generate a full URL with a unique code for lab registration.

        Uses the current lab's API URL to build the complete URL.

        :return: Full URL with unique code as query parameter
        :rtype: str
        """
        code = UniqueCodeService.generate_code_current_user(None, 300)
        base_url = Settings.get_instance().get_lab_api_url()
        return f"{base_url}/{Settings.core_api_route_path()}/lab/from-code?code={code}"

    @classmethod
    def register_lab_from_url(cls, url: str) -> LabDTO:
        """Register this lab to another lab using a code URL.

        Called on the second lab with this lab information, and the URL containing
        the code generated by the first lab. The service extracts the code,

        Then receives the first lab's response to create/update the lab and credentials on this second lab,
        and returns the first lab's response.

        :param url: The full URL containing the code (generated by the first lab)
        :type url: str
        :return: LabDTO with credentials data returned by the first lab
        :rtype: LabDTOWithCredentials
        """

        # Call the first lab's /lab/from-code endpoint
        lab_dto = LabModel.get_or_create_current_lab().to_dto()
        response = ExternalApiService.post(url, body=lab_dto, raise_exception_if_error=True)

        lab_with_creds = LabDTOWithCredentials.from_json(response.json())

        return cls._create_or_update_lab_with_credentials(
            lab_with_creds.lab, lab_with_creds.credentials_data
        ).to_dto()

    @classmethod
    def create_or_update_lab_from_code(cls, code: str, lab_dto: LabDTO) -> LabDTOWithCredentials:
        """Create or update a lab from a unique code.

        Validates and consumes the code, creates/updates the lab,
        and ensures credentials exist for it.

        :param code: The unique code to validate
        :type code: str
        :param lab_dto: DTO with lab information
        :type lab_dto: LabDTO
        :return: LabDTO with credentials data
        :rtype: LabDTOWithCredentials
        """
        # Validate and consume the code
        code_object = UniqueCodeService.check_code(code)

        user = User.get_by_id_and_check(code_object.user_id)

        with AuthenticateUser(user):
            # Create or update the remote lab (Lab B) and its credentials on this lab (Lab A)
            remote_lab = cls._create_or_update_lab_with_credentials(lab_dto)

            # Return this lab's (Lab A) info with the credentials that the remote lab (Lab B)
            # should use to communicate with this lab
            current_lab = LabModel.get_or_create_current_lab()
            return LabDTOWithCredentials(
                lab=current_lab.to_dto(),
                credentials_data=remote_lab.get_credentials_data(),
            )

    @classmethod
    def _create_or_update_lab_with_credentials(
        cls, lab_dto: LabDTO, lab_credentials: CredentialsDataLab | None = None
    ) -> LabModel:
        """Create or update a lab model and its credentials"""
        # Create or update the lab
        lab = LabModel.get_or_create_from_dto(lab_dto)

        # No linked credentials yet — get or create by name
        credentials = cls._get_or_create_lab_credentials(lab, lab_credentials)
        lab.credentials = credentials
        lab.save()

        return lab

    @classmethod
    def _get_or_create_lab_credentials(
        cls, lab: LabModel, lab_credentials: CredentialsDataLab | None = None
    ) -> Credentials:
        """Get or create LAB credentials for a lab by name.

        If credentials with the name already exist, return them as-is
        (the caller is responsible for updating the type if needed).

        :param lab: The lab model
        :type lab: LabModel
        :return: The credentials
        :rtype: Credentials
        """

        name: str
        # if the credentials already exist, keep the name
        if lab.credentials:
            name = lab.credentials.name
        else:
            name = CredentialsService.generate_unique_name(f"Lab {lab.name} - {lab.mode.value}")

        if not lab_credentials:
            lab_credentials = CredentialsDataLab(api_key=StringHelper.generate_random_chars(30))

        # Generate random api_key and create credentials
        save_dto = SaveCredentialsDTO(
            name=name,
            type=CredentialsDataLab.get_type_id(),
            description=f"Credentials for lab {lab.name}, mode : {lab.mode.value}",
            data=lab_credentials.to_json_dict(),
        )

        if lab.credentials:
            return CredentialsService.update(lab.credentials.id, save_dto)
        else:
            return CredentialsService.create(save_dto)

    ############################ GET #############################
    @classmethod
    def get_by_id(cls, id_: str) -> LabModel:
        """Get a lab by its database id.

        :param id_: The database id of the lab
        :type id_: str
        :return: The lab model
        :rtype: LabModel
        """
        return LabModel.get_by_id_and_check(id_)

    ############################ REFRESH #############################
    @classmethod
    def refresh_external_lab(cls, id_: str) -> LabModel:
        """Refresh the locally stored information of an external lab.

        Calls the external lab's credentials-secured ``/lab-info`` route (using the
        credentials stored for that lab) to fetch its up-to-date information, then
        updates the local LabModel row accordingly.

        :param id_: The database id of the external lab to refresh
        :type id_: str
        :raises BadRequestException: If the lab is the current lab, or has no
            credentials/domain configured for external communication
        :return: The updated lab model
        :rtype: LabModel
        """
        lab = LabModel.get_by_id_and_check(id_)

        if lab.is_current_lab():
            raise BadRequestException("The current lab cannot be refreshed from an external lab.")

        # Ensures the lab has both credentials and a domain to reach it.
        lab.check_credentials_and_domain()

        api_service = ExternalLabApiService(lab.to_dto_with_credentials())
        lab_info = api_service.get_lab_info()

        # get_or_create_from_dto looks up by (lab_id, mode) and updates the changed fields.
        return LabModel.get_or_create_from_dto(lab_info)

    ############################ UPDATE #############################
    @classmethod
    def update_domain(cls, id_: str, domain: str) -> LabModel:
        """Update the domain of an external lab.

        Before persisting the new domain, the external lab's credentials-secured
        ``/lab-info`` route is called using the new domain (with the stored
        credentials) to verify that the lab is reachable at this domain and that
        the credentials still work. The domain is only saved if that call succeeds.

        :param id_: The database id of the external lab to update
        :type id_: str
        :param domain: The new domain to set
        :type domain: str
        :raises BadRequestException: If the lab is the current lab or has no
            credentials configured
        :return: The updated lab model
        :rtype: LabModel
        """
        lab = LabModel.get_by_id_and_check(id_)

        if lab.is_current_lab():
            raise BadRequestException("The current lab domain cannot be updated from an external lab.")

        if not lab.has_credentials():
            raise BadRequestException(
                GWSException.LAB_MISSING_CREDENTIALS_OR_DOMAIN.value,
                GWSException.LAB_MISSING_CREDENTIALS_OR_DOMAIN.name,
                {"lab_name": lab.name},
            )

        # Build a DTO carrying the new domain (but the stored credentials) so the
        # client targets the new domain. The call raises if the lab is unreachable
        # at this domain or the credentials are invalid, leaving the row untouched.
        lab_dto = lab.to_dto_with_credentials()
        lab_dto.lab = lab_dto.lab.model_copy(update={"domain": domain})
        ExternalLabApiService(lab_dto).get_lab_info()

        # The new domain is verified, persist it.
        lab.domain = domain
        lab.save()

        return lab

    ############################ DELETE #############################
    @classmethod
    def delete(cls, id_: str) -> None:
        """Delete a lab by its database id.

        Before deleting, verify that the lab is not referenced by any other
        entity through a blocking foreign key. If it is still used somewhere,
        the deletion is prevented and a ``BadRequestException`` is raised.

        References checked (foreign keys pointing to the lab):
          - ``TaskModel.run_by_lab`` / ``ProtocolModel.run_by_lab``
            (concrete tables of the abstract ``ProcessModel``)
          - ``SharedScenario.lab`` / ``SharedResource.lab``
          - ``Scenario.running_in_external_lab``

        :param id_: The database id of the lab to delete
        :type id_: str
        :raises BadRequestException: If the lab is still referenced somewhere
        """
        lab = LabModel.get_by_id_and_check(id_)

        cls._check_lab_not_used(lab)

        lab.delete_instance()

    @classmethod
    def _check_lab_not_used(cls, lab: LabModel) -> None:
        """Verify that the lab is not referenced by any blocking foreign key.

        :param lab: The lab model to check
        :type lab: LabModel
        :raises BadRequestException: If the lab is still referenced somewhere
        """
        # ProcessModel is abstract; its concrete tables are TaskModel and ProtocolModel.
        if TaskModel.select().where(TaskModel.run_by_lab == lab.id).exists():
            cls._raise_lab_used(lab, "task(s)")

        if ProtocolModel.select().where(ProtocolModel.run_by_lab == lab.id).exists():
            cls._raise_lab_used(lab, "protocol(s)")

        if Scenario.select().where(Scenario.running_in_external_lab == lab.id).exists():
            cls._raise_lab_used(lab, "scenario(s) running in this lab")

        if SharedScenario.select().where(SharedScenario.lab == lab.id).exists():
            cls._raise_lab_used(lab, "shared scenario(s)")

        if SharedResource.select().where(SharedResource.lab == lab.id).exists():
            cls._raise_lab_used(lab, "shared resource(s)")

    @classmethod
    def _raise_lab_used(cls, lab: LabModel, used_by: str) -> None:
        raise BadRequestException(
            f"The lab '{lab.name}' cannot be deleted because it is still used by {used_by}."
        )

    @classmethod
    def search(
        cls, search: SearchParams, page: int = 0, number_of_items_per_page: int = 20
    ) -> Paginator[LabModel]:
        """Search labs using a search builder.

        :param search: The search parameters
        :type search: SearchParams
        :param page: The page number
        :type page: int
        :param number_of_items_per_page: The number of items per page
        :type number_of_items_per_page: int
        :return: Paginated lab results
        :rtype: Paginator[LabModel]
        """
        search_builder = LabModelSearchBuilder()
        return search_builder.add_search_params(search).search_page(page, number_of_items_per_page)
