from urllib.parse import parse_qs, urlparse

from gws_core.core.classes.paginator import Paginator
from gws_core.core.classes.search_builder import SearchBuilder, SearchParams
from gws_core.core.service.external_api_service import ExternalApiService
from gws_core.core.utils.settings import Settings
from gws_core.core.utils.string_helper import StringHelper
from gws_core.credentials.credentials import Credentials
from gws_core.credentials.credentials_service import CredentialsService
from gws_core.credentials.credentials_type import (
    CredentialsDataBase,
    CredentialsDataLab,
    CredentialsType,
    SaveCredentialsDTO,
)
from gws_core.lab.lab_model.lab_dto import CreateLabFromCodeDTO, LabDTO, LabDTOWithCredentials
from gws_core.lab.lab_model.lab_model import LabModel
from gws_core.lab.lab_model.lab_model_search_builder import LabModelSearchBuilder
from gws_core.user.current_user_service import AuthenticateUser
from gws_core.user.unique_code_service import UniqueCodeService
from gws_core.user.user import User


class LabModelService:
    """Service for lab model operations with unique-code-based URL generation."""

    @classmethod
    def generate_unique_code_url(cls) -> str:
        """Generate a full URL with a unique code for lab registration.

        Uses the current lab's API URL to build the complete URL.

        :return: Full URL with unique code as query parameter
        :rtype: str
        """
        code = UniqueCodeService.generate_code_current_user(None, 300)
        base_url = Settings.get_instance().get_lab_api_url()
        return f"{base_url}/{Settings.core_api_route_path()}/lab/from-code?code={code}"

    @classmethod
    def register_lab_from_url(cls, url: str) -> LabDTO:
        """Register this lab to another lab using a code URL.

        Called on the second lab with this lab information, and the URL containing
        the code generated by the first lab. The service extracts the code,

        Then receives the first lab's response to create/update the lab and credentials on this second lab,
        and returns the first lab's response.

        :param url: The full URL containing the code (generated by the first lab)
        :type url: str
        :return: LabDTO with credentials data returned by the first lab
        :rtype: LabDTOWithCredentials
        """

        # Call the first lab's /lab/from-code endpoint
        lab_dto = LabModel.get_or_create_current_lab().to_dto()
        response = ExternalApiService.post(url, body=lab_dto, raise_exception_if_error=True)

        lab_with_creds = LabDTOWithCredentials.from_json(response.json())

        return cls._create_or_update_lab_with_credentials(
            lab_with_creds, lab_with_creds.credentials_data
        ).to_dto()

    @classmethod
    def create_or_update_lab_from_code(cls, code: str, lab_dto: LabDTO) -> LabDTOWithCredentials:
        """Create or update a lab from a unique code.

        Validates and consumes the code, creates/updates the lab,
        and ensures credentials exist for it.

        :param code: The unique code to validate
        :type code: str
        :param lab_dto: DTO with lab information
        :type lab_dto: LabDTO
        :return: LabDTO with credentials data
        :rtype: LabDTOWithCredentials
        """
        # Validate and consume the code
        code_object = UniqueCodeService.check_code(code)

        user = User.get_by_id_and_check(code_object.user_id)

        with AuthenticateUser(user):
            # Create or update the lab and its credentials
            return cls._create_or_update_lab_with_credentials(lab_dto).to_dto_with_credentials()

    @classmethod
    def _create_or_update_lab_with_credentials(
        cls, lab_dto: LabDTO, lab_credentials: CredentialsDataLab | None = None
    ) -> LabModel:
        """Create or update a lab model and its credentials"""
        # Create or update the lab
        lab = LabModel.get_or_create_from_dto(lab_dto)

        # No linked credentials yet — get or create by name
        credentials = cls._get_or_create_lab_credentials(lab, lab_credentials)
        lab.credentials = credentials
        lab.save()

        return lab

    @classmethod
    def _get_or_create_lab_credentials(
        cls, lab: LabModel, lab_credentials: CredentialsDataLab | None = None
    ) -> Credentials:
        """Get or create LAB credentials for a lab by name.

        If credentials with the name already exist, return them as-is
        (the caller is responsible for updating the type if needed).

        :param lab: The lab model
        :type lab: LabModel
        :return: The credentials
        :rtype: Credentials
        """

        name: str
        # if the credentials already exist, keep the name
        if lab.credentials:
            name = lab.credentials.name
        else:
            name = CredentialsService.generate_unique_name(f"Lab {lab.name} - {lab.mode.value}")

        if not lab_credentials:
            lab_credentials = CredentialsDataLab(api_key=StringHelper.generate_random_chars(30))

        # Generate random api_key and create credentials
        save_dto = SaveCredentialsDTO(
            name=name,
            type=CredentialsType.LAB,
            description=f"Credentials for lab {lab.name}, mode : {lab.mode.value}",
            data=lab_credentials.to_json_dict(),
        )

        if lab.credentials:
            return CredentialsService.update(lab.credentials.id, save_dto)
        else:
            return CredentialsService.create(save_dto)

    ############################ GET #############################
    @classmethod
    def get_by_id(cls, id_: str) -> LabModel:
        """Get a lab by its database id.

        :param id_: The database id of the lab
        :type id_: str
        :return: The lab model
        :rtype: LabModel
        """
        return LabModel.get_by_id_and_check(id_)

    @classmethod
    def search(
        cls, search: SearchParams, page: int = 0, number_of_items_per_page: int = 20
    ) -> Paginator[LabModel]:
        """Search labs using a search builder.

        :param search: The search parameters
        :type search: SearchParams
        :param page: The page number
        :type page: int
        :param number_of_items_per_page: The number of items per page
        :type number_of_items_per_page: int
        :return: Paginated lab results
        :rtype: Paginator[LabModel]
        """
        search_builder: SearchBuilder = LabModelSearchBuilder()
        return search_builder.add_search_params(search).search_page(page, number_of_items_per_page)
