

from typing import List

from fastapi import Depends
from fastapi.responses import RedirectResponse
from starlette.responses import JSONResponse, Response

from gws_core.core.exception.exceptions.unauthorized_exception import \
    UnauthorizedException
from gws_core.core.model.model_dto import PageDTO
from gws_core.core.service.front_service import FrontService
from gws_core.lab.dev_env_service import DevEnvService
from gws_core.user.auth_context import AuthContext, AuthContextUser
from gws_core.user.authentication_service import AuthenticationService
from gws_core.user.current_user_service import CurrentUserService
from gws_core.user.jwt_service import JWTService
from gws_core.user.user_dto import UserDTO, UserFullDTO

from ..core_controller import core_app
from .authorization_service import AuthorizationService
from .user_credentials_dto import UserCredentials2Fa, UserCredentialsDTO
from .user_service import UserService


@core_app.get("/user/me", tags=["User"])
def read_user_me(_=Depends(AuthorizationService.check_user_access_token)) -> UserFullDTO:
    """
    Get current user details.
    """

    return CurrentUserService.get_and_check_current_user().to_full_dto()


@core_app.post("/login", tags=["User"], summary="Login to the lab by requesting space")
def login(credentials: UserCredentialsDTO) -> Response:
    """
    Log the user using space
    """

    return AuthenticationService.login(credentials)


@core_app.post("/login-2fa", tags=["User"], summary="Login 2FA to the lab by requesting space")
def login_2_fa(credentials: UserCredentials2Fa) -> Response:
    """
    Login 2FA to the lab by requesting space
    """

    return AuthenticationService.login_with_2fa(credentials)


@core_app.get("/check-token", tags=["User"], summary="Check user's token")
def check_token(auth_context: AuthContext = Depends(AuthorizationService.check_user_access_token)) -> str:
    """Simple route to check the user's token (used in automatic dev login), returns the user's id if valid
    """
    return auth_context.get_user().id


@core_app.get("/login-temp-access/{unique_code}", tags=["User"],
              summary="Log the user from the temp access token generated by space")
def login_from_temp_token(unique_code: str) -> Response:

    try:
        auth_context = AuthorizationService.check_unique_code(unique_code)

        response = RedirectResponse(FrontService.get_auto_login_url(JWTService.get_token_duration_in_milliseconds()))
        return AuthenticationService.log_user(auth_context.get_user(), response=response)
    except Exception:
        # if there is any problem redirect to the front base url (login)
        return RedirectResponse(FrontService.get_front_url())


@core_app.post("/dev-login/{code}", tags=["User"], summary="Login to the dev lab using an unique code")
def dev_login(code: str) -> Response:
    """
    Log the user on the dev lab by calling the prod api, using a temp code generated by the prod api
    """

    return DevEnvService.dev_get_check_user(code)


@core_app.get("/dev-login-unique-code/generate", tags=["User"],
              summary="Generate a temp unique code to login to the dev lab")
def generate_dev_login_unique_code(auth_context: AuthContext = Depends(AuthorizationService.check_user_access_token)) -> str:
    """
    Generate a temp unique code to login to the dev lab
    """
    if not isinstance(auth_context, AuthContextUser):
        raise UnauthorizedException("Only users can generate dev login unique codes")
    return DevEnvService.generate_dev_login_unique_code(auth_context.get_user().id)


@core_app.post("/dev-login-unique-code/check/{unique_code}", tags=["User"],
               summary="Check the temp unique code to login to the dev lab")
def check_dev_login_unique_code(unique_code: str) -> UserFullDTO:
    """
    Check the temp unique code to login to the dev lab
    """
    return DevEnvService.check_dev_login_unique_code(unique_code).to_full_dto()


@core_app.post("/logout", tags=["User"], summary="Logout the user")
def logout() -> JSONResponse:
    """
    Logout
    """

    return AuthenticationService.logout()


@core_app.get("/user", tags=["User"])
def get_all_users(_=Depends(AuthorizationService.check_user_access_token)) -> List[UserDTO]:
    """
    List the users.
    """

    users = UserService.get_all_real_users()
    return [user.to_dto() for user in users]


@core_app.post("/user/synchronize", tags=["User"])
def synchronize_users(_=Depends(AuthorizationService.check_user_access_token)) -> None:
    """
    Synchronize the folders from space
    """

    UserService.synchronize_all_space_users()


@core_app.get("/user/{id}", tags=["User"])
def get_by_id_and_check(id: str,
                        _=Depends(AuthorizationService.check_user_access_token)) -> UserDTO:
    return UserService.get_by_id_and_check(id).to_dto()


@core_app.get("/user/name-search/{name}", tags=["User"])
def search_user_by_name(name: str,
                        page: int = 0,
                        number_of_items_per_page: int = 20,
                        _=Depends(AuthorizationService.check_user_access_token_or_app)) -> PageDTO[UserDTO]:
    """
    Search users by name
    """
    return UserService.smart_search_by_name(name, page, number_of_items_per_page).to_dto()
